### PR TITLE
broadcasting events based on navigator actions

### PR DESCRIPTION
**Pull request by ericraio**

### CODE REVIEW

**Comment by ericraio** [comment]
@sethx I added the events here but I am still trying to figure out how to emit the pop event when you swipe to go back. Any ideas?

**Comment by charpeni** [comment]
`goBackwards` ?

**Comment by davidLeonardi** [comment]
@ericraio You're saying that adding an emitter to onBack doesn't do the trick?

**Comment by davidLeonardi** [comment]
Ah i see what's going on.
Seems that the "back" swipe is handled directly by the Navigator.
`this.navigationContext.emit('willfocus', {route: route});` is how this occurs, in Navigator.js .

EventEmitter.js is what is actually the emitter implementation. 
I _hope_ this works with fbemitter, if not we should switch this to using the emitter provided by RN instead of fbemitter.

**Comment by davidLeonardi** [comment]
@charpeni @ericraio On second thought I've been having issues with fbemitter lately, mainly because it also is included by "flux" , but at a 0.1 alpha something version, which breaks my local packer.
So how about we just switch to the emitter used by RN instead?
The emitter implementation can be found here: react-native/Libraries/vendor/emitter/EventEmitter.js

What the router can then do, is listen to this emitted event, and emit an event itself, essentially becoming the main emitter for routing/navigation.

Thoughts?

**Comment by davidLeonardi** [comment]
Merging this and will implement the change for this myself.

**Comment by ericraio** [comment]
@sethx @charpeni 
Hey guys, just catching up on the updates. I like the idea better of using RN event emitter and replacing another dependency.

Yeah, I was wondering how to tap into navigators swipe to go back.

What's really nice about this approach is that it gives the developer the ability to add a ref to the router itself and respond to all push or pop events.

For people who use redux, they can maintain the state whenever a route changes if they chose to

```javascript
componentDidMount() {
  this.refs.router.emitter.addListener("push", (route) => {
    // perform an operation for every push
  })
}

render() {
  return (
    <Router
      ref={"router"}
      ...
    />
  );
}
```

**Pull request merged**
